name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  check-conflicts:
    runs-on: ubuntu-latest

    steps:
      - name: 내 브랜치로 이동
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: 메인으로 체크아웃
        uses: actions/checkout@v3
        with:
          ref: main
          path: main_branch

      - name: 충돌체크
        run: |
          git fetch origin main
          git merge --no-commit --no-ff origin/main || echo "::error::Merge conflict detected" && exit 1

  build:
    needs: check-conflicts
    runs-on: ubuntu-latest
    if: success() 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: JDK 세팅
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 빌드
        run: mvn clean install

      - name: 테스트
        run: mvn test
